
project_id = "ntmogcnenelmbggucipy"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = true

[functions.search-nfts]
verify_jwt = false

[functions.generate-nft-image]
verify_jwt = false

[functions.seed-nfts]
verify_jwt = false
