// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntmogcnenelmbggucipy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bW9nY25lbmVsbWJnZ3VjaXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njg0ODMsImV4cCI6MjA1ODE0NDQ4M30.CbYxmzJxiOiI7aON5GTtZgAlO9-4Ycb-FaYJT4D7oWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);